/*
 *  swtamodule.cpp
 */

#include "swtamodule.h"

// Generated includes:
#include "config.h"

// include headers with your own stuff
#include "stdp_connection_sem.h"
#include "swta_neuron_dbl_exp.h"

// Includes from nestkernel:
#include "connection_manager_impl.h"
#include "connector_model_impl.h"
#include "dynamicloader.h"
#include "exceptions.h"
#include "genericmodel.h"
#include "genericmodel_impl.h"
#include "kernel_manager.h"
#include "model.h"
#include "model_manager_impl.h"
#include "nestmodule.h"
#include "target_identifier.h"

// Includes from sli:
#include "booldatum.h"
#include "integerdatum.h"
#include "sliexceptions.h"
#include "tokenarray.h"

// -- Interface to dynamic module loader ---------------------------------------

/*
 * There are three scenarios, in which SWTAModule can be loaded by NEST:
 *
 * 1) When loading your module with `Install`, the dynamic module loader must
 * be able to find your module. You make the module known to the loader by
 * defining an instance of your module class in global scope. (LTX_MODULE is
 * defined) This instance must have the name
 *
 * <modulename>_LTX_mod
 *
 * The dynamicloader can then load modulename and search for symbol "mod" in it.
 *
 * 2) When you link the library dynamically with NEST during compilation, a new
 * object has to be created. In the constructor the DynamicLoaderModule will
 * register your module. (LINKED_MODULE is defined)
 *
 * 3) When you link the library statically with NEST during compilation, the
 * registration will take place in the file `static_modules.h`, which is
 * generated by cmake.
 */
#if defined( LTX_MODULE ) | defined( LINKED_MODULE )
swtamodule_ns::SWTAModule swtamodule_LTX_mod;
#endif
// -- DynModule functions ------------------------------------------------------

swtamodule_ns::SWTAModule::SWTAModule()
{
#ifdef LINKED_MODULE
  // register this module at the dynamic loader
  // this is needed to allow for linking in this module at compile time
  // all registered modules will be initialized by the main app's dynamic loader
  nest::DynamicLoaderModule::registerLinkedModule( this );
#endif
}

swtamodule_ns::SWTAModule::~SWTAModule()
{
}

const std::string
swtamodule_ns::SWTAModule::name( void ) const
{
  return std::string( "SWTA Module" ); // Return name of the module
}

const std::string
swtamodule_ns::SWTAModule::commandstring( void ) const
{
  // Instruct the interpreter to load swtamodule-init.sli
  return std::string( "(swtamodule-init) run" );
}

//-------------------------------------------------------------------------------------

void
swtamodule_ns::SWTAModule::init( SLIInterpreter* i )
{
  // register neuron models
  nest::kernel().model_manager.register_node_model<swta_neuron_dbl_exp>("swta_neuron_dbl_exp");

  // register synapse models
  nest::kernel().model_manager.register_connection_model<STDPConnectionSem<nest::TargetIdentifierPtrRport> >("sem_synapse");

} // SWTAModule::init()
